### ISSUE TITLE
No animation after player enters a house

### ISSUE THREAD

**Issue by Damjandeveloper133** [Gdevelop-game/GDevelop-Open-Game#37] opened 2020-06-22 16:59 UTC
I come near any house  then i press a and then enter and the animation that gets in the house dosen't play and then the fading effect  happens but it results a black screen

**Comment by the-gem-dev** [comment] 2020-06-22 18:36
could you share a video on this please

**Comment by PawBud** [comment] 2020-06-22 20:03
This happens to me to, I thought that we have progressed only so far? (Sorry I didn’t really open the game too often so I am unaware of every detail )

**Comment by the-gem-dev** [comment] 2020-06-22 21:29
I would work on that soon

**Comment by the-gem-dev** [comment] 2020-06-23 16:55
it should be fixed by now

**Comment by PawBud** [comment] 2020-06-25 15:23
https://streamable.com/bbwd6h I think it still persists? 

GDevelop version:- Beta-89.00
OS:- Linux 20.04 LTS

**Comment by PawBud** [comment] 2020-06-25 15:23
Sorry if I am doing something wrong, in that case, you may close this issue :)

**Comment by the-gem-dev** [comment] 2020-06-25 17:03
can you share a video about this

**Comment by PawBud** [comment] 2020-06-26 07:49
Just to rectify, This is not a bug according to @the-gem-dev and the video is https://streamable.com/bbwd6h

**Closed** 2020-06-26 07:49 UTC
Labels: bug

**Comment by the-gem-dev** [comment] 2020-06-26 08:41
Once the game is done our player won't be able to preview the rooms scene without entering a door in the overworked scene
